export enum ChatActions {
  CONNECT = 'CHAT/CONNECT',
  DISCONNECT = 'CHAT/DISCONNECT',
  JOIN_CHAT = 'CHAT/JOIN_CHAT',
  LEAVE_CHAT = 'CHAT/LEAVE_CHAT',
  SEND_MESSAGE = 'CHAT/SEND_MESSAGE',
  VIEW_MESSAGES = 'CHAT/VIEW_MESSAGES'
}

export enum ChatManagerActions {
  CONNECT = 'CHAT_MANAGER/CONNECT',
  DISCONNECT = 'CHAT_MANAGER/DISCONNECT',
  CREATE_GROUP = 'CHAT_MANAGER/CREATE_GROUP',
  GET_CHATS = 'CHAT_MANAGER/GET_CHATS',
  GET_DIALOGS = 'CHAT_MANAGER/GET_DIALOGS',
  SEARCH_CHATS = 'CHAT_MANAGER/SEARCH_CHATS',
  SEARCH_DIALOGS = 'CHAT_MANAGER/SEARCH_DIALOGS'
}

export enum FolderManagerActions {
  CONNECT = 'FOLDER_MANAGER/CONNECT',
  DISCONNECT = 'FOLDER_MANAGER/DISCONNECT',
  CREATE_FOLDER = 'FOLDER_MANAGER/CREATE_FOLDER',
  GET_FOLDERS = 'FOLDER_MANAGER/GET_FOLDERS',
  EDIT_FOLDER = 'FOLDER_MANAGER/EDIT_FOLDER',
  SEARCH_FOLDER_CHATS = 'SEARCH_FOLDER_CHATS',
  DELETE_FOLDER = 'FOLDER_MANAGER/DELETE_FOLDER',
}